### ISSUE TITLE
better lower orbits needed

### ISSUE THREAD

**Issue by PilotAstronomy** [Qwarkk6/CLS#10]
The orbits this does w/ fairly little effort are all very high. An 80-120km orbit is more common in KSP

**Comment by Qwarkk6** [comment]
Are you referring to the ‘default’ orbit CLS aims for, or are you finding the script fails to achieve lower orbits when you specify that during pre-launch?

Earlier versions of this were designed for stock KSP and therefore aimed for 100km orbits by default. Current versions will work on stock but are designed for RSS in which the atmosphere finishes at 140km but targets 250km by default.

**Comment by PilotAstronomy** [comment]
Maybe that’s my problem. I’m playing on stock. Should I refer to earlier
version? It does achieve low orbits but not efficiently w dV or time.

**Comment by Qwarkk6** [comment]
Time efficiency was never a goal of CLS and later versions sacrificed some dV efficiency in order to improve the script's reliability of getting to orbit with any ship design I threw at it. 
I can't really recommend earlier versions as they have some major bugs that can result in the script terminating mid flight. I dont have a bunch of free time at the moment, but I will take a look when I can.
Out of interest, what data suggests poor dV efficiency? Have you compared a launch with CLS to a manual launch / how much dV was saved compared to CLS?
